<?xml version="1.0" encoding="utf-8"?><Database Name="E-tender" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=E-tender;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="E_tenderConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Admin" Member="Admins">
    <Type Name="Admin">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AdminId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AdminPassword" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Company" Member="Companies">
    <Type Name="Company">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CCompanyId" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ContactNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ProfilePhoto" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Company_Tender" Member="Tenders" ThisKey="CCompanyId" OtherKey="CCompanyId" Type="Tender" />
      <Association Name="Company_TenderResponse" Member="TenderResponses" ThisKey="CCompanyId" OtherKey="CCompanyId" Type="TenderResponse" />
    </Type>
  </Table>
  <Table Name="dbo.Tender" Member="Tenders">
    <Type Name="Tender">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[Tender Registration Number]" Member="Tender_Registration_Number" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Tender Name]" Member="Tender_Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Tender Documents]" Member="Tender_Documents" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="[Tender Quation ]" Member="Tender_Quation_" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CCompanyId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Company_Tender" Member="Company" ThisKey="CCompanyId" OtherKey="CCompanyId" Type="Company" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TenderResponse" Member="TenderResponses">
    <Type Name="TenderResponse">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SCompanyId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SCompanyName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Quotation" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Duration" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CCompanyId" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Company_TenderResponse" Member="Company" ThisKey="CCompanyId" OtherKey="CCompanyId" Type="Company" IsForeignKey="true" />
      <Association Name="Supplier_TenderResponse" Member="Supplier" ThisKey="SCompanyId" OtherKey="SCompanyId" Type="Supplier" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Supplier" Member="Suppliers">
    <Type Name="Supplier">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SCompanyId" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SCompanyName" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Quotation" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Image" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IsActive" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Supplier_TenderResponse" Member="TenderResponses" ThisKey="SCompanyId" OtherKey="SCompanyId" Type="TenderResponse" />
    </Type>
  </Table>
</Database>